Add hometask-1
Muhamob/smart-home-2019 pull request #1
Opened 2019-10-10 20:18 UTC by Muhamob

2019-10-10 21:47 UTC, Muhamob commented
Юсов Александр

2019-10-15 22:35 UTC, a-ivanov requested changes

2019-10-15 22:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeUtils/HomeReader.java
> +    public SmartHome readHome(String path) throws IOException;
Детали имплементации отражены в абстракции (leaky abstraction). Исправьте.

2019-10-15 22:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          SensorEvent event = getNextSensorEvent();
Нарушен SRP: получение события - это отдельная responsibility. Исправьте.

2019-10-15 22:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +public class EventList {
Подумайте, нужна ли эта абстракция? Что она моделирует? Нужно ли нам в будущем заменять эту функциональность другой имплементацией?

2019-10-15 22:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +    private static List<EventHandler> eventHandlers = Arrays.asList(
Подумайте, что является абстракцией, а что - конфигурационным кодом и перенесите каждое в свое место.

2019-10-15 22:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventDoor.java
> +                            if (room.getName().equals("hall")) {
Нарушен SRP - обработка события двери и выполнение сценария "умного дома". Исправьте.

2019-10-17 12:03 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +public class EventList {
Исправил на то, как я это вижу и понимаю в коммите https://github.com/Muhamob/smart-home-2019/pull/1/commits/4f69e3bcdeaa80f3c949ab2cfdf6d8a33b8576bf

2019-10-17 12:32 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          SensorEvent event = getNextSensorEvent();
Исправил. Также создал новый интерфейс для получения событий. https://github.com/Muhamob/smart-home-2019/pull/1/commits/462e265427f8ac811b315099d089c1ac5e1ef72c

2019-10-21 21:55 UTC, a-ivanov requested changes
Не доделаны несколько предыдущих требований.

2019-10-21 21:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeUtils/HomeReader.java
> +    public SmartHome readHome(String path) throws IOException;
Не исправлено.

2019-10-21 21:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventDoor.java
> +                            if (room.getName().equals("hall")) {
Не исправлено.

2019-10-21 21:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventHandlerEnum.java
> +Чтобы добавить ещё одно событие нужно дописать EVENTSMTH(new EventSmth());
А зачем так усложнять конфигурацию? Какие от этого кода плюсы в сравнении с просто создать EventHandler в главном конфигурационном коде?

2019-10-23 20:23 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventDoor.java
> +                            if (room.getName().equals("hall")) {
Имеет ли смысл исправлять, если уже переделано в 2-ом задании?

2019-10-23 20:33 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventHandlerEnum.java
> +Чтобы добавить ещё одно событие нужно дописать EVENTSMTH(new EventSmth());
В данном случае, наверное можно и list сделать. Однако в следующих домашних заданиях мне показалось более правильным использовать такую структуру.

2019-10-24 07:17 UTC, a-ivanov requested changes
Либо перенесите все исправления по 1 дз в эту ветку, либо оставьте эту ветку и сделайте все исправления в ветке 2 дз. Выберите один из вариантов и сделайте из него request changes. Сейчас сложно проверять.

2019-10-24 07:17 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private SmartHome readHome(String path) throws IOException{
Читать состояние дома должна какая-то одна абстракция, сейчас не понятно, кто это делает.

2019-10-24 07:17 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Это отдельная responsibility, исправьте.

2019-10-24 07:17 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventHandlerEnum.java
> +Чтобы добавить ещё одно событие нужно дописать EVENTSMTH(new EventSmth());
Чем конкретно более правильно?

2019-10-24 08:23 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Отдельная responsibility получения следующего события?

2019-10-24 09:10 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Если так, то у меня уже существуют различные eventSource с одним общим методом getNextSensorEvent

2019-10-24 10:02 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventHandlerEnum.java
> +Чтобы добавить ещё одно событие нужно дописать EVENTSMTH(new EventSmth());
Это не слишком большое усложнение конфигурационного кода.
Переделал так, чтобы в конфигурационном коде хранились классы необходимых Action. Однако получается более громоздкий код, который итерируется по всем действияи

2019-10-24 10:11 UTC, Muhamob commented
> Либо перенесите все исправления по 1 дз в эту ветку, либо оставьте эту ветку и сделайте все исправления в ветке 2 дз. Выберите один из вариантов и сделайте из него request changes. Сейчас сложно проверять.

request review?

2019-10-24 15:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Нет, я про логику с циклом обработки событий - While цикл

2019-10-24 15:17 UTC, a-ivanov commented
Да request review, напишите в чате, в какую ветку смотреть.

2019-10-24 20:25 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Исправил. Можно посмотреть в этой ветке или в hometask-2 или в hometask-3

2019-10-26 17:41 UTC, a-ivanov commented
Этот реквест еще актуален? Все правки по 1му заданию есть в https://github.com/Muhamob/smart-home-2019/pull/2? Если да, то закройет этот реквест и не просите ревью.

2019-10-26 22:49 UTC, closed without merging