Домашнее задание, 3'я неделя
Muhamob/smart-home-2019 pull request #3
Opened 2019-10-24 17:01 UTC by Muhamob

2019-10-27 20:14 UTC, a-ivanov requested changes
Поправьте сначала замечания по 1 и 2 дз.

2019-11-08 15:12 UTC, a-ivanov requested changes

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            if (smartHome.getSmartDevice(smartHome.getAlarmId()) != null) {
Нарушение SRP. С сигнализацией должен работать обработчик событий, сейчас эта функция внутри класса с циклом событий.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sources/EventSourceManger.java
> +            EventList.run(smartHome, event);
Нарушение OCP. А если захотим вызывать обработчики по-другому, а не через EventList.run? Сделайте зависимостью.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +            System.out.println("Sending sms");
Почему смс отправляется здесь и в ActionWhileAlarmAlertDecorator? Надо делать это где-то в одном месте, DRY принцип.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sources/EventManager.java
> +    public void manage(SmartHome smartHome);
Плохое название метода, непонятно, что он делает, конкретизируйте.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sources/EventSource.java
> +    public SensorEvent getNextSensorEvent();
В интерфейсах все методы public по умолчанию.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Interior.java
> +    public SmartDevice getSmartDevice(String id) {
Не надо делать методы с доступом ко внутреннему сотсоянию только для тестов. Уберите их и подобные и пользуйтесь только execute.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Interior.java
> +            if (floor.contains(id)) return true;
Floor должен сам выполнять цикл обработки внутри сам без доступа к его внутренним объектам - в этом смысл 2го задания.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Floor.java
> +            if (room.contains(id)) return true;
Room не должна давать доступ к своим внутренностям, в этом смысл задания 2.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/HomeComponent.java
> +    public SmartDevice getSmartDevice(String id);
Уберите эти методы из интерфейса, мы работаем с внутренним итератором execute только, в этом суть 2го дз.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Floor.java
> +        for (Room room : rooms) {
Почему тогда Floor не дает выполнить действие над ним самим, а только над комнатами?

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/ActionEnum.java
> +public enum ActionEnum {
А если мы захотим добавить несколько обработчиков на одно и то же событие? В текущем решении это сделать нельзя. Эту и исходную проблему можно решить путем переноса ответственности маппинга типа события из захардкоженного в enum'е в отдельный класс обработчика. Исправьте.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Exterior.java
> +
Опять же, с Exterior тоже можно совершать действия.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +                Alarm alarm = (Alarm) smartHome.getSmartDevice(smartHome.getAlarmId());
Уберите метод getSmartDevice, по 2му заданию мы отказываемся от раскрытия внутренностей объектов дома.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            smartHome.execute(action);
Запуск action над элементами дома - это отдельная ответственность, сейчас тут нарушение SRP.

2019-11-08 15:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/AlarmState.java
> +public abstract class AlarmState {
Перечитайте 3е задание. В интерфейсе состояния должны присутствовать 3 метода на каждое действие с сигнализацией. Переделывайте.

2019-11-29 22:20 UTC, a-ivanov requested changes

2019-11-29 22:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/AlarmActivated.java
> +public class AlarmActivated extends AlarmState {
Чем AlarmActivated отличается от AlarmActivated от AlarmAlert? Они же делают все одно и то же, перечитайте, как надо имплементировать паттерн состояние. Откажитесь от абстрактного класса, сделайте интерфейс состояния и имплементируйте три класса на каждое из состояний.

2019-11-29 22:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            Alarm alarm = AlarmUtils.getAlarm(smartHome);
Ненужный трюк, можно либо создать сигнализацию вне дома, можно в доме геттер объявить с сигнализацией.

2019-11-29 22:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            smartHome.execute(action);
Комментарий выше все еще актуален, EventList максимум запускает обработку событий над списком обработчиком, переделайте.

2019-11-29 22:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +                if (alarm.isActivated()) {
Вся логика с сигнализацией и ее состоянием - внутри декоратора.

2019-12-01 12:04 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/sources/EventSourceManger.java
> +            EventList.run(smartHome, event);
Испрваил в https://github.com/Muhamob/smart-home-2019/pull/3/commits/00b00bc73e92457907ade0f584ac2c1efe9a9036. Теперь, если возникает необходимость вызывать обаботчики по-другому, нужно создать соответствующий класс, который будет реализовывать интерфейс EventManeger

2019-12-01 12:28 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            if (smartHome.getSmartDevice(smartHome.getAlarmId()) != null) {
Исправил в https://github.com/Muhamob/smart-home-2019/pull/3/commits/491efc4a48cf554adf1496e38c3b96cb1c6abc55. Сейчас обёртывание действия происходит во время создания этих действий

2019-12-01 13:10 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +            System.out.println("Sending sms");
Исправил в https://github.com/Muhamob/smart-home-2019/pull/3/commits/aa7dcef0b03dce7b59753a6048acf5c00d9f195e . Теперь существует отдельный SmartDevice SMSSender, который отпарвляет в случае срабатывания сигнализации смс

2019-12-01 13:14 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/sources/EventManager.java
> +    public void manage(SmartHome smartHome);
Исправил название в https://github.com/Muhamob/smart-home-2019/pull/3/commits/93ca51d873e03185818bdf1980847c3cbb6d54af . EventProcessor может быть звучит лучше чем EventManager

2019-12-01 13:15 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Interior.java
> +    public SmartDevice getSmartDevice(String id) {
Исправил в https://github.com/Muhamob/smart-home-2019/commit/aa7dcef0b03dce7b59753a6048acf5c00d9f195e . Добавил класс HomeUtils, который имеет методы для получения SmartDevice по id или классу

2019-12-01 13:18 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/sources/EventSource.java
> +    public SensorEvent getNextSensorEvent();
Не знал. Исправил в https://github.com/Muhamob/smart-home-2019/pull/3/commits/9daed6e180c330579d8614f9c2a327b4579cd557

2019-12-01 13:19 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Interior.java
> +            if (floor.contains(id)) return true;
Floor теперь нет

2019-12-01 13:20 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Floor.java
> +            if (room.contains(id)) return true;
Исправлено в https://github.com/Muhamob/smart-home-2019/pull/3/commits/47fb25258e563bbd383d2841fbdcf8f673de90cb

2019-12-01 13:20 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/HomeComponent.java
> +    public SmartDevice getSmartDevice(String id);
Исправлено в https://github.com/Muhamob/smart-home-2019/pull/3/commits/47fb25258e563bbd383d2841fbdcf8f673de90cb

2019-12-01 13:20 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Floor.java
> +        for (Room room : rooms) {
Исправлено в https://github.com/Muhamob/smart-home-2019/pull/3/commits/47fb25258e563bbd383d2841fbdcf8f673de90cb

2019-12-01 13:21 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/ActionEnum.java
> +public enum ActionEnum {
Испрвлено в https://github.com/Muhamob/smart-home-2019/pull/3/commits/8c83a3afae4d9ef16e35e884d89773eb3920ce44

2019-12-01 13:21 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/homeStructure/Exterior.java
> +
Удалено

2019-12-01 13:21 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +                Alarm alarm = (Alarm) smartHome.getSmartDevice(smartHome.getAlarmId());
Исправлено в https://github.com/Muhamob/smart-home-2019/commit/47fb25258e563bbd383d2841fbdcf8f673de90cb

2019-12-01 15:17 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            Alarm alarm = AlarmUtils.getAlarm(smartHome);
Переделал в https://github.com/Muhamob/smart-home-2019/commit/aa7dcef0b03dce7b59753a6048acf5c00d9f195e

2019-12-01 15:20 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +                if (alarm.isActivated()) {
Переделал в https://github.com/Muhamob/smart-home-2019/commit/491efc4a48cf554adf1496e38c3b96cb1c6abc55

2019-12-01 16:23 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/devices/AlarmActivated.java
> +public class AlarmActivated extends AlarmState {
Переделал в https://github.com/Muhamob/smart-home-2019/pull/3/commits/699a181cc640d26ec074f0f32ea738c498a12b20

2019-12-01 16:39 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            smartHome.execute(action);
Немного не поинмаю почему этот код нарушает SRP, может быть я назвал класс запутанно. Однако, в этом классе происходит только запуск всех action

2019-12-23 14:26 UTC, a-ivanov requested changes

2019-12-23 14:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/alarm/AlarmActivated.java
> +        // Логично, что если кто-то попытается ещё раз активировать сигнализацию
Не логично, этого добавлять было не обязательно.

2019-12-23 14:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventList.java
> +            smartHome.execute(action);
Да, я не сразу понял из-за названия класса HomeComponentAction (думал - это имплементация самого действия из 2го дз). Лучше переименовать HomeComponentAction в EventProcessor, а EventProcessor в EventLoopRunner, имплементация может носить название ListLoopRunner.

2019-12-23 14:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/utils/HomeUtils.java
> +    public static SmartDevice getSmartDevice(Actionable actionable, Class clazz) {
Зачем это все, если можно просто добавить геттер в доме на сигнализацию? Зачем так абстрактно?

2019-12-23 14:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventCollectionCreator.java
> +        for (HomeComponentAction action : getDefaultActionList(event)) {
Весь for блок - это нарушение OCP, в этом классе максимум создание списка обработчиков. Логика по запуску обработки - в обработчиках.

2019-12-23 14:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +        boolean executed = wrappee.execute(homeComponent);
По заданию декоратор должен а) контролировать запуск дальнейших обработчиков в зависимости от статуса сигнализации и б) отправлять смс. Здесь непонятно, при каких условиях будет запущен wrappee. Я вижу, что ему дают запускаться всегда. Бизнес логика не ложна зависеть от конфигурации, переделайте.

2019-12-23 16:21 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/utils/HomeUtils.java
> +    public static SmartDevice getSmartDevice(Actionable actionable, Class clazz) {
Я принял данное решение, так как иначе если делать геттер в доме, это значит, что в самом объекте дома необходимо создать новое поле с сигнализацией, что противоречит принципу dependency inversion(если я правильно понимаю), так как при добавлении всего лишь одного нового смарт-девайса, приходится переписывать класс, который, по идее, не должен страдать/изменятся от добавления нового смарт-девайса. Поэтому сигнализация в моём решении является обычным девайсом в том смысле, что он может находится где угодно, а соответственно, чтобы его использовать, его нужно найти в доме. Для этого и существует данная функция

2019-12-23 16:31 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventCollectionCreator.java
> +        for (HomeComponentAction action : getDefaultActionList(event)) {
В данном классе действия только создаются и максимум оборачиваются декоратором

2019-12-23 16:36 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +        boolean executed = wrappee.execute(homeComponent);
Да, wrappee будет запускаться всегда, однако дело в том, что не всегда действия оборачиваются данным декоратором. В классе EventCollectionCreator определяется будет ли действие обёрнуто в данный декоратор или нет в соответствии с бизнес-логикой.

2019-12-23 17:00 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/devices/alarm/AlarmActivated.java
> +        // Логично, что если кто-то попытается ещё раз активировать сигнализацию
Изменил в https://github.com/Muhamob/smart-home-2019/pull/3/commits/3bd98a1920012e6a136c15b73ea6d0e3baa5a066

2019-12-30 12:07 UTC, a-ivanov requested changes

2019-12-30 12:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/utils/HomeUtils.java
> +    public static SmartDevice getSmartDevice(Actionable actionable, Class clazz) {
Все объекты дома - доменные классы, их API известен изначально по ТЗ и не должен сильно меняться. В них можно легко добавить геттеры с конкретными объектами, это сильно упрощает API и работу с ними.

2019-12-30 12:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventCollectionCreator.java
> +        for (HomeComponentAction action : getDefaultActionList(event)) {
Здесь написана часть логики декоратора, ее надо перенести в код декоратора. Сделайте один декоратор, зачем два узкоспециализированных класса, которые тяжело переиспользовать.

2019-12-30 12:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +        boolean executed = wrappee.execute(homeComponent);
У вас логика декоратора разнесена на два класса + конфигурационный класс, который "настраивает" декораторы. Должно быть все в одном классе декоратора. Здесь нарушается OCP, SRP (другие классы делают не свою работу). Переделайте.

2019-12-30 14:02 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/utils/HomeUtils.java
> +    public static SmartDevice getSmartDevice(Actionable actionable, Class clazz) {
fd57261

2019-12-30 14:03 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/EventCollectionCreator.java
> +        for (HomeComponentAction action : getDefaultActionList(event)) {
e33d6c6

2019-12-30 14:03 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/ActionWhileAlarmActivatedDecorator.java
> +        boolean executed = wrappee.execute(homeComponent);
e33d6c6

2020-01-19 20:18 UTC, a-ivanov requested changes

2020-01-19 20:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                if (wrappee.getClass() != AlarmAction.class) {
Проверка класса wrappee - это нарушение OCP, вам должно быть достаточно проверить состояние сигнализации и тип события. Так вы привязываетесь к конкретному классу обработчика, переделайте.

2020-01-19 20:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                if (wrappee.getClass() != AlarmAction.class) {
Проверка класса wrappee - это нарушение OCP, вам должно быть достаточно проверить состояние сигнализации и тип события. Так вы привязываетесь к конкретному классу обработчика, переделайте.

2020-01-19 21:48 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                if (wrappee.getClass() != AlarmAction.class) {
Поправил в 
d1693d3

2020-01-21 11:11 UTC, a-ivanov requested changes

2020-01-21 11:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                    result = executeWhileActivated(actionable);
Ну так а в чем логика? Тут если AlarmActivated, то любое событие кроме ALARM_DEACTIVATE будет обработано. Смотрите задание 3, там необходимо прерывать обработку событий при активной сигнализации.

2020-01-21 11:56 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                    result = executeWhileActivated(actionable);
Нет, в данном случае вызывается метод executeWhileAlarmActivated, который переключает сигнализацию в режим тревоги и отправляет смс

2020-01-21 12:17 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/actions/AlarmDecorator.java
> +                    result = executeWhileActivated(actionable);
Ошибся, не заметил, что там действительно исполняется действие в первой строчке. Исправил в 368bde6

2020-01-25 17:23 UTC, closed without merging