Hometask 4
Muhamob/smart-home-2019 pull request #4
Opened 2019-11-07 21:05 UTC by Muhamob

2020-01-19 20:31 UTC, a-ivanov requested changes

2020-01-19 20:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Main.java
> +        Application app = context.getBean(Application.class);
См. как должен выглядеть main метод в лекции 6, там цикл обработки запускается через класс из сторонней библиотеки.

2020-01-19 20:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/configs/NewAPIConfig.java
> +    public Application getApplication() {
Этот класс не нужен в конфигурации, надо использовать SensorEventManager.

2020-01-19 20:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/EventManagerConverter.java
> +        sensorEventsManager.registerEventHandler(event -> {
Это должно настраиваться в конфигурации. И здесь необходимо по заданию регистрировать адаптер. Адаптер, как видно из названия, адаптирует один интерфейс к другому. У вас он конвертирует события. Перечитайте задание и исправьте.

2020-01-21 11:23 UTC, a-ivanov requested changes

2020-01-21 11:23 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/LightEventHandlerAdapter.java
> +public class LightEventHandlerAdapter implements EventHandler {
По заданию необходимо было создать минимальное количество кода для интеграции с сторонней библиотекой. Сделайте один адаптер интерфейса EventHandler, который будет делегировать написанным до этого обработчикам.

2020-01-21 12:46 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/adapters/LightEventHandlerAdapter.java
> +public class LightEventHandlerAdapter implements EventHandler {
Обработчикам событий в качестве аргументов при создании необходим сам event, которые с данным API нельзя передать непосредственно в цикле обработчику событий. И здесь есть два выхода, которые я вижу: использовать Reflection (что наверное не безопасно) или создание собственного адаптера для каждого из обработчиков.

2020-01-22 14:36 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/LightEventHandlerAdapter.java
> +public class LightEventHandlerAdapter implements EventHandler {
Все правильно - event конвертируется в событие нужного типа и передается предыдущим обарботчикам. И это все в одном адаптере. Это все на лекция сотню раз обсуждалось, еще и с разными вариантами имплементации...

2020-01-22 17:08 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/adapters/LightEventHandlerAdapter.java
> +public class LightEventHandlerAdapter implements EventHandler {
Переделал в 22012ca

2020-01-22 18:10 UTC, a-ivanov requested changes

2020-01-22 18:10 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/EventAdapter.java
> +        switch (event.getEventType()) {
Это нарушение OCP: добавление новых обработчиков потребует модификацию кода с бизнес логикой. Пути решения конечно же также обсуждались на лекциях: цепочка обязанностей конвертеров, либо мапа с строковым ключем на конвертер.

2020-01-22 18:10 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/EventAdapter.java
> +public class EventAdapter implements SensorEventAdapter {
Это не адаптер - он не адаптирует никакой интерфейс, это конвертер. Переименуйте его соответственно.

2020-01-22 18:32 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/configs/NewAPIConfig.java
> +    SensorEventConverter getEventConverter() {
Бины не надо называть как геттеры, просто тот объект, который они создают.

2020-01-22 18:34 UTC, a-ivanov approved these changes

2020-01-25 17:23 UTC, closed without merging