Hometask-5
Muhamob/smart-home-2019 pull request #5
Opened 2019-11-07 21:06 UTC by Muhamob

2019-12-30 12:11 UTC, a-ivanov requested changes

2019-12-30 12:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Main.java
> +        HomeReader homeReader = new JsonHomeReader();
Где использование спринга по 4-5 заданию? См. как должен выглядеть main метод в лекции к заданию 4.

2019-12-30 14:04 UTC, Muhamob commented on src/main/java/ru/sbt/mipt/oop/Main.java
> +        HomeReader homeReader = new JsonHomeReader();
Данная домашняя работа на данный момент не сделана. 4-ую домашнюю работу можно посмотреть в соответствующем pull request'е

2020-01-21 13:39 UTC, Muhamob commented
Создаю новый pull request, так как так как лучше мержить в другую ветку

2020-01-21 13:39 UTC, closed without merging